import { createPublicKey, diffieHellman } from 'crypto';
import { describe, expect, it } from 'vitest';

import {
	ResponseOpener,
	SecureChannelError,
	SecureSession,
	addressFromPublicKey,
	base64urlDecode,
	deriveSessionKeys,
	domainHash,
	establishClientSession,
	makeClientHello,
	nonceForSequence,
	open,
	openBufferedResponse,
	recoverAddress,
	requestAAD,
	responseAAD,
	responseKey,
	seal,
	transcriptPayload,
	x25519PrivateKeyFromRaw,
	x25519PublicKeyFromRaw,
	x25519RawPublicKey,
} from '../src/secureChannel';
import vectors from './vectors/secure-channel-v1-vectors.json';

/**
 * Known-answer suite shared with the Osaurus Swift test
 * `SecureChannelVectorsTests`. The JSON is generated by Swift
 * (`OSAURUS_WRITE_SC_VECTORS=1`) and copied here verbatim; if either side
 * changes the protocol, both suites go red.
 */
const hs = vectors.handshake;
const hello = hs.clientHello;
const serverHello = hs.serverHello;

describe('secure channel v1 vectors: transcript and identity', () => {
	it('builds the canonical transcript', () => {
		expect(transcriptPayload(hello, serverHello).toString('utf8')).toBe(hs.transcript);
	});

	it('computes the domain-separated keccak hash', () => {
		expect(domainHash(Buffer.from(hs.transcript, 'utf8')).toString('hex')).toBe(hs.domainHashHex);
	});

	it('recovers the agent address from the transcript signature', () => {
		const sig = Buffer.from(serverHello.signature.slice(2), 'hex');
		expect(recoverAddress(Buffer.from(hs.transcript, 'utf8'), sig)).toBe(vectors.agent.address);
	});

	it('checksums addresses per EIP-55', () => {
		// Recompute from the recovered key path to make sure the checksum
		// casing matches Swift's `checksummedAddress`.
		const sig = Buffer.from(serverHello.signature.slice(2), 'hex');
		const recovered = recoverAddress(Buffer.from(hs.transcript, 'utf8'), sig);
		expect(recovered).toBe(vectors.agent.address);
		expect(recovered).not.toBe(recovered.toLowerCase());
	});
});

describe('secure channel v1 vectors: key schedule', () => {
	it('derives the client ephemeral public key from the fixed private key', () => {
		const priv = x25519PrivateKeyFromRaw(Buffer.from(hs.clientEphemeralPrivateHex, 'hex'));
		expect(x25519RawPublicKey(createPublicKey(priv)).toString('base64url')).toBe(hello.encPub);
		const serverPriv = x25519PrivateKeyFromRaw(Buffer.from(hs.serverEphemeralPrivateHex, 'hex'));
		expect(x25519RawPublicKey(createPublicKey(serverPriv)).toString('base64url')).toBe(
			serverHello.encPub,
		);
	});

	it('agrees on the X25519 shared secret and HKDF session keys', () => {
		const priv = x25519PrivateKeyFromRaw(Buffer.from(hs.clientEphemeralPrivateHex, 'hex'));
		const serverPub = x25519PublicKeyFromRaw(base64urlDecode(serverHello.encPub));
		const shared = diffieHellman({ privateKey: priv, publicKey: serverPub });
		expect(Buffer.from(shared).toString('hex')).toBe(hs.sharedSecretHex);
		const keys = deriveSessionKeys(shared, Buffer.from(hs.transcript, 'utf8'));
		expect(keys.c2s.toString('hex')).toBe(hs.clientToServerKeyHex);
		expect(keys.s2c.toString('hex')).toBe(hs.serverToClientKeyHex);
	});

	it('derives the per-call response key', () => {
		const s2c = Buffer.from(hs.serverToClientKeyHex, 'hex');
		expect(responseKey(s2c, vectors.bufferedResponse.requestSeq).toString('hex')).toBe(
			vectors.bufferedResponse.responseKeyHex,
		);
		expect(responseKey(s2c, vectors.streamResponse.requestSeq).toString('hex')).toBe(
			vectors.streamResponse.responseKeyHex,
		);
	});
});

describe('secure channel v1 vectors: AEAD framing', () => {
	it('uses 4 zero bytes || big-endian u64 as the nonce and the documented AADs', () => {
		expect(nonceForSequence(vectors.call.requestSeq).toString('hex')).toBe(vectors.call.nonceHex);
		expect(requestAAD(serverHello.sid, vectors.call.requestSeq).toString('utf8')).toBe(
			vectors.call.aad,
		);
		expect(
			responseAAD(
				serverHello.sid,
				vectors.bufferedResponse.requestSeq,
				vectors.bufferedResponse.frame.seq,
				true,
			).toString('utf8'),
		).toBe(vectors.bufferedResponse.frame.aad);
	});

	it('seals the request byte-for-byte like Swift', () => {
		const c2s = Buffer.from(hs.clientToServerKeyHex, 'hex');
		const ct = seal(
			c2s,
			vectors.call.requestSeq,
			requestAAD(serverHello.sid, vectors.call.requestSeq),
			Buffer.from(vectors.call.innerRequest, 'utf8'),
		);
		expect(ct).toBe(vectors.call.ct);
	});

	it('opens the buffered fin frame with the per-call key', () => {
		const key = Buffer.from(vectors.bufferedResponse.responseKeyHex, 'hex');
		const frame = vectors.bufferedResponse.frame;
		const plaintext = open(key, frame.seq, Buffer.from(frame.aad, 'utf8'), frame.ct);
		expect(plaintext.toString('utf8')).toBe(frame.plaintext);
	});

	it('opens the streamed frames in order and refuses post-fin frames', () => {
		const s2c = Buffer.from(hs.serverToClientKeyHex, 'hex');
		const opener = new ResponseOpener(
			serverHello.sid,
			vectors.streamResponse.requestSeq,
			responseKey(s2c, vectors.streamResponse.requestSeq),
		);
		const frames = vectors.streamResponse.frames;
		for (const frame of frames) {
			const { plaintext, fin } = opener.open({ seq: frame.seq, ct: frame.ct, fin: frame.fin });
			expect(plaintext.toString('utf8')).toBe(frame.plaintext);
			expect(fin).toBe(frame.fin);
		}
		expect(opener.finished).toBe(true);
		expect(() => opener.open({ seq: frames.length, ct: frames[0].ct })).toThrow(SecureChannelError);
	});

	it('rejects a frame under the wrong AAD (fin flipped)', () => {
		const key = Buffer.from(vectors.bufferedResponse.responseKeyHex, 'hex');
		const frame = vectors.bufferedResponse.frame;
		const wrongAad = responseAAD(
			serverHello.sid,
			vectors.bufferedResponse.requestSeq,
			frame.seq,
			false,
		);
		expect(() => open(key, frame.seq, wrongAad, frame.ct)).toThrow(/decrypt/);
	});
});

describe('secure channel v1 vectors: end to end from fixed inputs', () => {
	it('reproduces the client hello and establishes the same session', () => {
		const { privateKey, hello: rebuilt } = makeClientHello(
			vectors.agent.address,
			Buffer.from(hs.clientEphemeralPrivateHex, 'hex'),
			base64urlDecode(hello.nonce),
		);
		expect(rebuilt).toEqual(hello);
		const session = establishClientSession(rebuilt, privateKey, serverHello, vectors.agent.address);
		expect(session.sid).toBe(serverHello.sid);
		const { call, requestSeq } = session.sealCall(JSON.parse(vectors.call.innerRequest));
		expect(requestSeq).toBe(vectors.call.requestSeq);
		expect(call).toEqual(vectors.call.body);
		const inner = openBufferedResponse(
			JSON.stringify(vectors.bufferedResponse.frame),
			session.makeResponseOpener(requestSeq),
		);
		expect(inner.status).toBe(200);
		expect(base64urlDecode(inner.body ?? '').toString('utf8')).toBe('{"status":"ok"}');
	});

	it('rejects the handshake when the pinned address differs', () => {
		const { privateKey, hello: rebuilt } = makeClientHello(
			vectors.agent.address,
			Buffer.from(hs.clientEphemeralPrivateHex, 'hex'),
			base64urlDecode(hello.nonce),
		);
		expect(() =>
			establishClientSession(
				rebuilt,
				privateKey,
				serverHello,
				'0x0000000000000000000000000000000000000001',
			),
		).toThrow(/identity mismatch/i);
	});

	it('rejects a tampered server ephemeral key', () => {
		const { privateKey, hello: rebuilt } = makeClientHello(
			vectors.agent.address,
			Buffer.from(hs.clientEphemeralPrivateHex, 'hex'),
			base64urlDecode(hello.nonce),
		);
		const tampered = { ...serverHello, encPub: rebuilt.encPub };
		expect(() =>
			establishClientSession(rebuilt, privateKey, tampered, vectors.agent.address),
		).toThrow(SecureChannelError);
	});

	it('exposes the agent address helper used by the checksum path', () => {
		// 0x04 || X || Y of the secp256k1 generator; checksum casing is what matters.
		const generator = Buffer.from(
			'0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8',
			'hex',
		);
		expect(addressFromPublicKey(generator)).toBe('0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf');
	});
});

describe('SecureSession bookkeeping', () => {
	it('starts request sequence numbers at 1 and honours the expiry margin', () => {
		const session = new SecureSession('sid', Buffer.alloc(32, 1), Buffer.alloc(32, 2), 1_000);
		expect(session.sealCall({ method: 'GET', path: '/' }).requestSeq).toBe(1);
		expect(session.sealCall({ method: 'GET', path: '/' }).requestSeq).toBe(2);
		expect(session.isUsable(1_000 - 61)).toBe(true);
		expect(session.isUsable(1_000 - 60)).toBe(false);
	});
});
